const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"老师项目类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLaoshixiangmu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"学生项目类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXueshengxiangmu"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"工作安排信息管理",
                        "menuJump":"列表",
                        "tableName":"gongzuoanpai"
                    }
                ],
                "menu":"工作安排信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"开闭幕式信息管理",
                        "menuJump":"列表",
                        "tableName":"kaibi"
                    }
                ],
                "menu":"开闭幕式信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"老师管理",
                        "menuJump":"列表",
                        "tableName":"laoshi"
                    }
                ],
                "menu":"老师管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"老师项目管理",
                        "menuJump":"列表",
                        "tableName":"laoshixiangmu"
                    }
                ],
                "menu":"老师项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"老师项目报名管理",
                        "menuJump":"列表",
                        "tableName":"laoshixiangmubaoming"
                    }
                ],
                "menu":"老师项目报名管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"赛事编排信息管理",
                        "menuJump":"列表",
                        "tableName":"saishibianpai"
                    }
                ],
                "menu":"赛事编排信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"xuesheng"
                    }
                ],
                "menu":"学生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生项目管理",
                        "menuJump":"列表",
                        "tableName":"xueshengxiangmu"
                    }
                ],
                "menu":"学生项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生项目报名管理",
                        "menuJump":"列表",
                        "tableName":"xueshengxiangmubaoming"
                    }
                ],
                "menu":"学生项目报名管理"
            }
            ,
			{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"裁判管理",
                        "menuJump":"列表",
                        "tableName":"caipan"
                    }
                ],
                "menu":"裁判管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"院系管理",
                        "menuJump":"列表",
                        "tableName":"yuanxi"
                    }
                ],
                "menu":"院系管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"工作安排信息管理",
                        "menuJump":"列表",
                        "tableName":"gongzuoanpai"
                    }
                ],
                "menu":"工作安排信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"开闭幕式信息管理",
                        "menuJump":"列表",
                        "tableName":"kaibi"
                    }
                ],
                "menu":"开闭幕式信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"老师项目管理",
                        "menuJump":"列表",
                        "tableName":"laoshixiangmu"
                    }
                ],
                "menu":"老师项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"老师项目报名管理",
                        "menuJump":"列表",
                        "tableName":"laoshixiangmubaoming"
                    }
                ],
                "menu":"老师项目报名管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"赛事编排信息管理",
                        "menuJump":"列表",
                        "tableName":"saishibianpai"
                    }
                ],
                "menu":"赛事编排信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"xuesheng"
                    }
                ],
                "menu":"学生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"学生项目管理",
                        "menuJump":"列表",
                        "tableName":"xueshengxiangmu"
                    }
                ],
                "menu":"学生项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"学生项目报名管理",
                        "menuJump":"列表",
                        "tableName":"xueshengxiangmubaoming"
                    }
                ],
                "menu":"学生项目报名管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"院系管理",
                        "menuJump":"列表",
                        "tableName":"yuanxi"
                    }
                ],
                "menu":"院系管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"裁判",
        "tableName":"caipan"
    }
	,{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"工作安排信息管理",
                        "menuJump":"列表",
                        "tableName":"gongzuoanpai"
                    }
                ],
                "menu":"工作安排信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"开闭幕式信息管理",
                        "menuJump":"列表",
                        "tableName":"kaibi"
                    }
                ],
                "menu":"开闭幕式信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"老师项目管理",
                        "menuJump":"列表",
                        "tableName":"laoshixiangmu"
                    }
                ],
                "menu":"老师项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"老师项目报名管理",
                        "menuJump":"列表",
                        "tableName":"laoshixiangmubaoming"
                    }
                ],
                "menu":"老师项目报名管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"赛事编排信息管理",
                        "menuJump":"列表",
                        "tableName":"saishibianpai"
                    }
                ],
                "menu":"赛事编排信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"xuesheng"
                    }
                ],
                "menu":"学生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生项目管理",
                        "menuJump":"列表",
                        "tableName":"xueshengxiangmu"
                    }
                ],
                "menu":"学生项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"学生项目报名管理",
                        "menuJump":"列表",
                        "tableName":"xueshengxiangmubaoming"
                    }
                ],
                "menu":"学生项目报名管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"院系管理",
                        "menuJump":"列表",
                        "tableName":"yuanxi"
                    }
                ],
                "menu":"院系管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"老师",
        "tableName":"laoshi"
    }
	,{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"工作安排信息管理",
                        "menuJump":"列表",
                        "tableName":"gongzuoanpai"
                    }
                ],
                "menu":"工作安排信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"开闭幕式信息管理",
                        "menuJump":"列表",
                        "tableName":"kaibi"
                    }
                ],
                "menu":"开闭幕式信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"赛事编排信息管理",
                        "menuJump":"列表",
                        "tableName":"saishibianpai"
                    }
                ],
                "menu":"赛事编排信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"学生项目管理",
                        "menuJump":"列表",
                        "tableName":"xueshengxiangmu"
                    }
                ],
                "menu":"学生项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"学生项目报名管理",
                        "menuJump":"列表",
                        "tableName":"xueshengxiangmubaoming"
                    }
                ],
                "menu":"学生项目报名管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"院系管理",
                        "menuJump":"列表",
                        "tableName":"yuanxi"
                    }
                ],
                "menu":"院系管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"学生",
        "tableName":"xuesheng"
    }
]
    }
}
export default menu;
